from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class HuntAssets: 


	# Click Rule Assets
	# description 
	C_HUNT_ENTER = RuleClick(roi_front=(1090,597,94,59), roi_back=(1090,597,94,59), name="hunt_enter")


	# Image Rule Assets
	# 神社 
	I_HUNT_SHRINE = RuleImage(roi_front=(870,624,65,61), roi_back=(870,624,65,61), threshold=0.8, method="Template matching", file="./tasks/Hunt/hunt/hunt_hunt_shrine.png")
	# 狩猎战 
	I_HUNT_HUNT = RuleImage(roi_front=(157,414,215,166), roi_back=(157,414,215,166), threshold=0.8, method="Template matching", file="./tasks/Hunt/hunt/hunt_hunt_hunt.png")


	# Image Rule Assets
	# 麒麟的挑战 
	I_KIRIN_CHALLAGE = RuleImage(roi_front=(1134,597,90,54), roi_back=(1134,597,90,54), threshold=0.8, method="Template matching", file="./tasks/Hunt/kirin/kirin_kirin_challage.png")
	# 集合 
	I_KIRIN_GATHER = RuleImage(roi_front=(28,480,75,64), roi_back=(28,480,75,64), threshold=0.8, method="Template matching", file="./tasks/Hunt/kirin/kirin_kirin_gather.png")
	# 麒麟已挑战 
	I_KIRIN_END = RuleImage(roi_front=(1126,601,104,44), roi_back=(1126,601,104,44), threshold=0.8, method="Template matching", file="./tasks/Hunt/kirin/kirin_kirin_end.png")


	# Image Rule Assets
	# 点击阴界之门
	# 8-09 修复: roi_back 原 (1060,602,100,100) 与模板 100x100 同尺寸、零容错,
	# 小号模拟器按钮偏移 1px(实测实际位置 1059,601)时 ROI 截掉模板边缘,
	# ROI 内匹配 0.764 < 0.8 阈值 → appear 判"不存在" → netherworld() 空转 60s 卡死重启
	# (8-09 主号陪1 实测, 与 8-05 AreaBoss 红叉 ROI 贴边同病)。扩大 roi_back 到
	# ±10px 容错, 滑窗匹配自动定位; 命中后运行时自动更新 roi_front 为精确位置
	I_NW = RuleImage(roi_front=(1050,592,120,120), roi_back=(1050,592,120,120), threshold=0.8, method="Template matching", file="./tasks/Hunt/netherworld/netherworld_nw.png")
	# 点击挑战
	# 8-09 同批加固: roi_back 加 ±10px 余量(原与模板同尺寸贴边)
	I_NW_CHALLAGE = RuleImage(roi_front=(296,580,191,83), roi_back=(296,580,191,83), threshold=0.8, method="Template matching", file="./tasks/Hunt/netherworld/netherworld_nw_challage.png")
	# 今日已挑战
	# 8-09 同批加固: roi_back 加 ±10px 余量
	I_NW_DONE = RuleImage(roi_front=(298,590,176,61), roi_back=(298,590,176,61), threshold=0.9, method="Template matching", file="./tasks/Hunt/netherworld/netherworld_nw_done.png")


